spring:
  application:
    name: gateway-server
  config:          
    import: "optional:configserver:http://localhost:8091/"
  cloud:
    gateway:
      discovery: # telling gateway server to connect with SD eureka server and locate all the details from microservices
        locator:
          enabled: false  # levarage the info present in SD eureka to forward all the request by creating default route configs
          lowerCaseServiceId: true  # converts the path of logical app name to lower case
      #HTTP Timeout configs
#      httpclient:  #applicable for all paths except circuit breaker configued [Can also specify to path for route in CB filter configs]
#        connect-timeout: 1000  #Time take by gateway server to get connection w/ microservice
#        response-timeout: 3s #Max time to receive response from microservice
        
management:  
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:  
    env:
      enabled: true
  
info:
  app:
    name: "gateway-server"
    description: "Entry point - API gateway for lab application"
    version: "1.0"

logging:
  level:
    com:
      lab:
        api:
          gateway: DEBUG

resilience4j.circuitbreaker:
    configs:
      default:   #applicable for all CB names and can also define for specific CB based on names set
        sliding-window-size: 10  #How many request to be monitored before Changing state from CLOSED to OPEN
        permitted-number-of-calls-in-half-open-state: 2 # Num.. of request to be allowed by HALF_OPEN state to decide and transit next state OPEN/CLOSED
        failure-rate-threshold: 50  # percentage of failed request (sliding-window-size) to change the state from CLOSED to OPEN
        wait-duration-in-open-state: 1000  # in ms remain in the open state for 1 second before transitioning to a half-open state to check if the service has recovered by allowing (permitted-number-of-calls-in-half-open-state) requests
      
            