global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8091' ]
  - job_name: 'lab-user-management'
    metrics_path: '/user/actuator/prometheus'
    static_configs:
      - targets: [ 'lab-user-management:8081' ]
  - job_name: 'lab-reports'
    metrics_path: '/reports/actuator/prometheus'
    static_configs:
      - targets: [ 'lab-reports:8080' ]
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eureka-server:8092' ]
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8093' ]
  
