server:
  port: 8081
  servlet:
    context-path: /user
spring:
  application:
    name: lab-user-management
  datasource:
    url: jdbc:postgresql://localhost:5432/laboratoryDB 
    username: root
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always   