server:
  port: 8080
  servlet:
    context-path: /reports
springdoc:
  packagesToScan: com.lab.reports.controller
spring:
  application:
    name: lab-reports
  datasource:
    url: jdbc:postgresql://localhost:5432/laboratoryDB 
    username: root
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  config:                                                  
    import: "optional:configserver:http://localhost:8091/"
# Hibernate ddl auto (create, create-drop, validate, update)
    #hibernate:
      #ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always    