spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://localhost:8091/"

management:  
  endpoints:
    web:
      exposure:
        include: "*"
  health:   
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:   
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
