spring:
  application:
    name: "config-server"
  profiles:
    active: native # activating the native profile of SCCS (USED WHEN WE STORE CONFIGS IN CLASS/FILE PATH)
#    active: git
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"  # scc server load all the properties from the classspath resources/config location. Run the application to check 
          #search-locations: "file:///D://MicroServices//Config" Load from file system||config file located at server location where MS is deployed. Advangtage : security to that folder to restrict user
#        git:    # Advantage: versioning to track previous changes || Read official docs to learn more https://docs.spring.io/spring-cloud-config/reference/server.html
#          uri: "https://github.com/vinodg8073/ms-configurations.git"
#          default-label: main #default branch
#          timeout: 5
#          clone-on-start: true #clone github repo at startup (if not provided clones at first request disadvantage: sometimes CS can be started but couldn't load the configs')
#          force-pull: true  #(at startup pulls latest changes when already cloned config has some changes made )

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
    
# To hit /monitor api (CS uses Spring cloud bus) || create github webhook to hit the api when changes made on config properties repository
management:  
  endpoints:
    web:
      exposure:
        include: "*"
  health:  # tells actuator to enable health related information 
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:  # enable the endpoint to read the health related information 
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}       
server:
  port: 8091
    
encrypt:     #Can encript, decrypt using same application based on below key using /encrypt , /decrypt endpoint
  key: 373HDS3828SHS7 # Any complex value || at real time configured from external