services:
  network-deploy-services: # seperated from microservice_base_configs because rabitmq
    networks:  
      - laboratory
  
  base_configs: 
    extends:
      service: network-deploy-services
    deploy:
      resources: 
        limits:
          memory: 700m
    # environment:
    #   SPRING_RABITMQ_HOST: "rabitmq" # This is service name not hostname for connection application.properties

  config_server_configs:
    extends:
      service: base_configs
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8091/ 
        
  
  microservice_depends_on_configs:
    extends:
      service: config_server_configs
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://laboratorydb:5432/laboratoryDB
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8092/eureka/
      SPRING_PROFILES_ACTIVE: prod  # set and use default env configs files while running locally
    
  