server:
  port: 8093

eureka:
  instance:
    preferIpAddress: true 
  client:
    fetch-registry: true 
    register-with-eureka: true 
    service-url:
      defaultZone: http://localhost:8092/eureka/

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"