server:
  port: 8080
  servlet:
    context-path: /reports

springdoc:
  packagesToScan: com.lab.reports.controller

spring:
  application:
    name: lab-reports
  datasource:
    url: jdbc:postgresql://localhost:5432/laboratoryDB 
    username: root
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always  

eureka:
  instance:
    preferIpAddress: true 
  client:
    fetch-registry: true 
    register-with-eureka: true 
    service-url:
      defaultZone: http://localhost:8092/eureka/
info:
  app:
    name: "lab-reports"
    description: "Report generator application"
    version: "1.0"

management:  
  endpoints:
    web:
      exposure:
        include: "*"
  info:  
    env:
      enabled: true
  health:   
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint: 
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true 
  metrics:
    tags:
      application: ${spring.application.name}
endpoints:
  shutdown:
    enabled: true 

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"  